@baseUri = http://localhost:3000
### AppControllerGetHello

# @name AppControllerGetHello

Get {{baseUri}}/home/hello

### ConceitosManualController HOME

# @name ConceitosManualController
Get {{baseUri}}/conceitos-manual

### ConceitosAutomáticosController HOME

# @name ConceitosAutomaticosController
Get {{baseUri}}/conceitos-automaticos/

# Verifique o valor de baseUri
# @name CheckBaseUri
Get {{baseUri}}