@baseUri = http://localhost:3000
### AppControllerGetHello

# @name AppControllerGetHello

Get {{baseUri}}/recados



###

GET {{baseUri}}/recados/1

###

POST {{baseUri}}/recados
Content-Type: application/json

  {
    
    "texto": "Este é o mais novo texto 3",
    "de": "Joao",
    "para": "Vitor",
    "lido": false,
    "data": "2025-01-14T19:41:54.460Z"
  }

###

PATCH {{baseUri}}/recados/1
Content-Type: application/json

  {
    "texto": "Este é o texto atualizado 2" ,
    "de": "mARIA",
    "para": "Vitor",
    "lido": false,
    "data": "2025-01-14T19:41:54.460Z"
  }

###

DELETE {{baseUri}}/recados/1